spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
server:
  port: 8070